#!/bin/bash

xsetwacom --set 'Wacom Intuos PT S 2 Pad pad' Button 8 "key -"
xsetwacom --set 'Wacom Intuos PT S 2 Pad pad' Button 9 "key +shift + -shift"
xsetwacom --set 'Wacom Intuos PT S 2 Pad pad' Button 1 "key +ctrl z -ctrl"
xsetwacom --set 'Wacom Intuos PT S 2 Pad pad' Button 3 "key +ctrl y -ctrl"
